# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170830_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_info',
            name='project_image_high_res',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
