# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_info_project_image_high_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_info',
            name='project_git',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project_info',
            name='project_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
