# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20171006_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_info',
            name='project_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
